language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: t3ddUSvhN1baJ6qaQPaxGioGIgAmKEsc4laK1jj4VfegrbrDzuEWp5N/rs6BDfj2ttcEdVZvYWCwR73aK6VXvpUpXFlvilXEUayjxwYamzxmORQ6aO3HOC82k7wWnzsjaIgD5KimNh4KiaE8HfEAoeZd0/QIj9+CLNIrBRNuqXtyI96UCBCgyr9S5KZ/9qRF4WKiZ5oZtLJdkigcJwyA6pYj/+TZbTtydnLqTwXO4kBQYacBGqgNEDsneRIvDaBUjQe7zFKch84krF5TsK2Eds7AZjrwEU8cCHg4QXrkvL+a40sza9CXIK5F7oNwpImpfmZBRswjFR0uAMRjHnwBiGKnFPPJ5W8Wh8NUTLre2wlBO9xWWDJ96d5xv3Xe8Tpcs2HFrWxSh2FVfLBvNlq0CcFnFRKdIz33ikanH8MHqFetp4xyOnp4Cm7nJREPRdoMYma6uTFq993Ir8tmZQNPofo3mQ6hv9j3b+ls9b1QrhaHmcZ/7yEHJCTAk8WAUT5vXJrPSREPLv9dxG2yazLpXSQtlNackDvNfr3d3Lqy/tqGdC/VV/X53igE/xYAwA4OESNKd7c3WjzxL0HZ3i5WnB1HOmd0pZs7PLA0Xd6vHq59z3ZKy8S9oBG60fzmMx+LQVEJrBMQrPKHnXv9qrQNAXVaDmbwYQ8k0eoCJmd6a+o=
  app: fast-everglades-42419

